
#Logging settings
[Logging]
	#Dictates if the mod stores explosion damage to the history log [Default: true]
	storeExplosions = true
	#Dictates if the mod stores interactions made with blocks that have a container (for example a chest) [Default: true]
	storeContainerInteractions = true
	#Dictates if the mod stores inventory interactions made with blocks that have an inventory (for example a chest) [Default: true]
	storeContainerInventoryChanges = true
	#The max amount of history stored per block [Default: 2147483647]
	#Range: > 1
	maxHistoryPerBlock = 2147483647
	#The max amount of history stored per block [Default: 10]
	#Range: 1 ~ 200
	maxHistoryInChat = 10

