#Max stack size per slot (-1 or 0 to use default). Going above 64 needs a mod like StackUp!.
#Range: > -1
maxStackSize = -1
#Items that cannot be placed down, in the format "modid:item_id" e.g. ["minecraft:carrot"]
#You can also use the plonk:unplaceable item tag as well.
unplaceableItems = []

