
#General Angel Ring 2 configuration options.
[general]
	#Define how much XP will be drained from player when flying by wearing classic Angel Ring? Put 0 if you need to disable XP requirement for flight.
	#Range: > 0
	XPCost = 5
	#Define how much ticks is required to pass between each XP drain event of classic Angel Ring?
	#Range: > 1
	TicksPerDrain = 50

