
[ore_protector]
	#If set to 'true' Piglins will protect Nether Ores
	piglinGuard = true
	#Set to false if you want the Piglins to attack when using Silk Touch Tools
	silkEffect = true
	#Set range that Piglins will aggro when mining ores(Default = 16)
	#Range: 0 ~ 64
	protectionRange = 16
	#Add Blocks to be protected by Piglins (Example: 'minecraft:glowstone')
	protectedBlocks = ["bno:nether_emerald_ore", "bno:nether_diamond_ore", "bno:nether_lapis_ore", "bno:nether_redstone_ore", "minecraft:nether_gold_ore", "bno:nether_silver_ore", "bno:nether_iron_ore", "bno:nether_lead_ore", "bno:nether_nickel_ore", "bno:nether_coal_ore", "bno:nether_copper_ore", "bno:nether_aluminum_ore", "bno:nether_tin_ore", "bno:nether_osmium_ore", "bno:nether_uranium_ore", "bno:nether_zinc_ore", "minecraft:glowstone", "minecraft:nether_quartz_ore"]

[ore_generation]

	[ore_generation.nickel]
		#Set Nickel Max Spawn Height (Default = 50)
		#Range: 0 ~ 256
		nickelMaxHeight = 50
		#Set Nickel Min Spawn Height (Default = 30)
		#Range: 0 ~ 250
		nickelMinHeight = 30
		#Set Max Nickel Vein Size (Default = 4)
		#Range: 0 ~ 32
		nickelVeinSize = 4
		#Set Nickel Spawn Chance (Default = 4)
		#Range: 0 ~ 64
		nickelChance = 0

	[ore_generation.osmium]
		#Set Osmium Min Spawn Height (Default = 30)
		#Range: 0 ~ 250
		osmiumMinHeight = 30
		#Set Osmium Max Spawn Height (Default = 75)
		#Range: 0 ~ 256
		osmiumMaxHeight = 75
		#Set Max Osmium Vein Size (Default = 8)
		#Range: 0 ~ 32
		osmiumVeinSize = 8
		#Set Osmium Spawn Chance (Default = 4)
		#Range: 0 ~ 64
		osmiumChance = 0

	[ore_generation.aluminum]
		#Set Aluminum Spawn Chance (Default = 4)
		#Range: 0 ~ 64
		aluminumChance = 0
		#Set Aluminum Max Spawn Height (Default = 110)
		#Range: 0 ~ 256
		aluminumMaxHeight = 110
		#Set Max Aluminum Vein Size (Default = 8)
		#Range: 0 ~ 32
		aluminumVeinSize = 8
		#Set Aluminum Min Spawn Height (Default = 75)
		#Range: 0 ~ 250
		aluminumMinHeight = 75

	[ore_generation.lead]
		#Set Lead Spawn Chance (Default = 4)
		#Range: 0 ~ 64
		leadChance = 0
		#Set Max Lead Vein Size (Default = 8)
		#Range: 0 ~ 32
		leadVeinSize = 8
		#Set Lead Max Spawn Height (Default = 110)
		#Range: 0 ~ 256
		leadMaxHeight = 110
		#Set Lead Min Spawn Height (Default = 40)
		#Range: 0 ~ 250
		leadMinHeight = 40

	[ore_generation.diamond]
		#Set Diamond Min Spawn Height (Default = 90)
		#Range: 0 ~ 250
		diamondMinHeight = 0
		#Set Diamond Spawn Chance (Default = 3)
		#Range: 0 ~ 32
		diamondChance = 2
		#Set Max Diamond Vein Size (Default = 8)
		#Range: 0 ~ 36
		diamondVeinSize = 8
		#Set Diamond Max Spawn Height (Default = 125)
		#Range: 0 ~ 256
		diamondMaxHeight = 250

	[ore_generation.world_generation]
		#Generate Nickel Ore
		nickel = false
		#Generate Osmium Ore
		osmium = false
		#Generate Aluminum Ore
		aluminum = false
		#Generate Lead Ore
		lead = false
		#Generate Diamond Ore
		diamond = true
		#Generate Tin Ore
		tin = false
		#Generate Coal Ore
		coal = true
		#Generate Iron Ore
		iron = true
		#Generate Copper Ore
		copper = true
		#Generate Lapis Ore
		lapis = true
		#Generate Silver Ore
		silver = false
		#Generate Uranium Ore
		uranium = false
		#Generate Zinc Ore
		zinc = false
		#Generate Emerald Ore
		emerald = true
		#Generate Redstone Ore
		redstone = true

	[ore_generation.tin]
		#Set Tin Min Spawn Height (Default = 40)
		#Range: 0 ~ 250
		tinMinHeight = 40
		#Set Tin Max Spawn Height (Default = 110)
		#Range: 0 ~ 256
		tinMaxHeight = 110
		#Set Max Tin Vein Size (Default = 8)
		#Range: 0 ~ 32
		tinVeinSize = 8
		#Set Tin Spawn Chance (Default = 3)
		#Range: 0 ~ 64
		tinChance = 0

	[ore_generation.coal]
		#Set Coal Max Spawn Height (Default = 115)
		#Range: 0 ~ 256
		coalMaxHeight = 256
		#Set Coal Min Spawn Height (Default = 25)
		#Range: 0 ~ 250
		coalMinHeight = 0
		#Set Max Coal Vein Size (Default = 17)
		#Range: 0 ~ 64
		coalVeinSize = 17
		#Set Coal Spawn Chance (Default = 20)
		#Range: 0 ~ 64
		coalChance = 20

	[ore_generation.iron]
		#Set Iron Max Spawn Height (Default = 110)
		#Range: 0 ~ 256
		ironMaxHeight = 256
		#Set Iron Spawn Chance (Default = 40)
		#Range: 0 ~ 64
		ironChance = 40
		#Set Iron Min Spawn Height (Default = 40)
		#Range: 0 ~ 250
		ironMinHeight = 0
		#Set Max Iron Vein Size (Default = 8)
		#Range: 0 ~ 32
		ironVeinSize = 8

	[ore_generation.copper]
		#Set Max Copper Vein Size (Default = 8)
		#Range: 0 ~ 32
		copperVeinSize = 8
		#Set Copper Spawn Chance (Default = 3)
		#Range: 0 ~ 64
		copperChance = 3
		#Set Copper Min Spawn Height (Default = 35)
		#Range: 0 ~ 250
		copperMinHeight = 0
		#Set Copper Max Spawn Height (Default = 75)
		#Range: 0 ~ 256
		copperMaxHeight = 250

	[ore_generation.lapis]
		#Set Lapis Min Spawn Height (Default = 30)
		#Range: 0 ~ 250
		lapisMinHeight = 0
		#Set Max Lapis Vein Size (Default = 7)
		#Range: 0 ~ 36
		lapisVeinSize = 7
		#Set Lapis Spawn Chance (Default = 2)
		#Range: 0 ~ 64
		lapisChance = 2
		#Set Lapis Max Spawn Height (Default = 60)
		#Range: 0 ~ 256
		lapisMaxHeight = 256

	[ore_generation.silver]
		#Set Silver Min Spawn Height (Default = 30)
		#Range: 0 ~ 250
		silverMinHeight = 30
		#Set Max Silver Vein Size (Default = 9)
		#Range: 0 ~ 64
		silverVeinSize = 9
		#Set Silver Spawn Chance (Default = 4)
		#Range: 0 ~ 64
		silverChance = 0
		#Set Silver Max Spawn Height (Default = 60)
		#Range: 0 ~ 256
		silverMaxHeight = 60

	[ore_generation.uranium]
		#Set Uranium Spawn Chance (Default = 2)
		#Range: 0 ~ 64
		uraniumChance = 0
		#Set Uranium Max Spawn Height (Default = 125)
		#Range: 0 ~ 256
		uraniumMaxHeight = 125
		#Set Uranium Min Spawn Height (Default = 90)
		#Range: 0 ~ 250
		uraniumMinHeight = 90
		#Set Max Uranium Vein Size (Default = 4)
		#Range: 0 ~ 32
		uraniumVeinSize = 4

	[ore_generation.zinc]
		#Set Zinc Min Spawn Height (Default = 55)
		#Range: 0 ~ 250
		zincMinHeight = 55
		#Set Max Zinc Vein Size (Default = 12)
		#Range: 0 ~ 32
		zincVeinSize = 12
		#Set Zinc Max Spawn Height (Default = 100)
		#Range: 0 ~ 256
		zincMaxHeight = 100
		#Set Zinc Spawn Chance (Default = 8)
		#Range: 0 ~ 64
		zincChance = 0

	[ore_generation.emerald]
		#Set Max Emerald Vein Size (Default = 4)
		#Range: 0 ~ 36
		emeraldVeinSize = 4
		#Set Emerald Spawn Chance (Default = 2)
		#Range: 0 ~ 32
		emeraldChance = 2
		#Set Emerald Max Spawn Height (Default = 55)
		#Range: 0 ~ 256
		emeraldMaxHeight = 256
		#Set Emerald Min Spawn Height (Default = 25)
		#Range: 0 ~ 250
		emeraldMinHeight = 0

	[ore_generation.redstone]
		#Set Redstone Spawn Chance (Default = 8)
		#Range: 0 ~ 64
		redstoneChance = 8
		#Set Redstone Max Spawn Height (Default = 115)
		#Range: 0 ~ 256
		redstoneMaxHeight = 256
		#Set Redstone Min Spawn Height (Default = 80)
		#Range: 0 ~ 250
		redstoneMinHeight = 0
		#Set Max Redstone Vein Size (Default = 8)
		#Range: 0 ~ 36
		redstoneVeinSize = 8

