#Stop mods from adding custom flowers
flowers = false
#Stop mods from adding surface structures
surface_structures = false
#Stop mods from adding entities
entities = false
#Stop mods from adding lakes
lakes = true

